/**
 * InterviewQuestions.jsx — Production-Level Interview Questions Panel
 * TrustLoom AI — Module 26
 *
 * Displays AI-generated interview questions with answers, grouped by category.
 * Features: expand/collapse, copy, download (PDF/TXT), regenerate, dark-theme aware.
 */

import React, { useState, useCallback, useMemo, useRef, useEffect } from "react";
import "./InterviewQuestions.css";

// ─── Category configuration ────────────────────────────────────────────────
const CATEGORY_CONFIG = {
  technical: {
    label: "Technical Questions",
    description: "Skill-based questions with expected answers",
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="16 18 22 12 16 6" /><polyline points="8 6 2 12 8 18" />
      </svg>
    ),
    color: "#3b82f6",
    gradient: "linear-gradient(135deg, #3b82f6, #2563eb)",
    light: "#dbeafe",
  },
  project: {
    label: "Project Deep-Dive",
    description: "Candidate-specific questions (no predefined answers)",
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" />
      </svg>
    ),
    color: "#f59e0b",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    light: "#fef3c7",
  },
  general: {
    label: "General / Behavioral",
    description: "Behavioral & situational questions with expected answers",
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M23 21v-2a4 4 0 0 0-3-3.87" /><path d="M16 3.13a4 4 0 0 1 0 7.75" />
      </svg>
    ),
    color: "#8b5cf6",
    gradient: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
    light: "#ede9fe",
  },
  red_flag: {
    label: "Red-Flag Clarifications",
    description: "Questions targeting detected concerns",
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" /><line x1="4" y1="22" x2="4" y2="15" />
      </svg>
    ),
    color: "#ef4444",
    gradient: "linear-gradient(135deg, #ef4444, #dc2626)",
    light: "#fee2e2",
  },
  behavioral: {
    label: "Behavioral",
    description: "Soft-skills & situational assessment",
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" /><path d="M8 14s1.5 2 4 2 4-2 4-2" /><line x1="9" y1="9" x2="9.01" y2="9" /><line x1="15" y1="9" x2="15.01" y2="9" />
      </svg>
    ),
    color: "#10b981",
    gradient: "linear-gradient(135deg, #10b981, #059669)",
    light: "#d1fae5",
  },
};

const DIFFICULTY_CONFIG = {
  junior: { label: "Junior", color: "#10b981", bg: "#d1fae5" },
  mid:    { label: "Mid",    color: "#f59e0b", bg: "#fef3c7" },
  senior: { label: "Senior", color: "#ef4444", bg: "#fee2e2" },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getCatConfig(key) {
  return CATEGORY_CONFIG[key] || CATEGORY_CONFIG.general;
}

function getDiffConfig(level) {
  return DIFFICULTY_CONFIG[level?.toLowerCase()] || DIFFICULTY_CONFIG.mid;
}

/** Build plain-text for clipboard / download */
function buildPlainText(categories) {
  const lines = [];
  lines.push("═".repeat(60));
  lines.push("  INTERVIEW QUESTIONS — Generated by TrustLoom AI");
  lines.push("  " + new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
  lines.push("═".repeat(60));
  lines.push("");

  const orderedCats = Object.keys(categories);
  let globalIndex = 1;

  orderedCats.forEach((catKey) => {
    const cfg = getCatConfig(catKey);
    const qs = categories[catKey];
    if (!qs || qs.length === 0) return;

    lines.push("─".repeat(60));
    lines.push(`  ${cfg.label.toUpperCase()}  (${qs.length} question${qs.length > 1 ? "s" : ""})`);
    lines.push("─".repeat(60));
    lines.push("");

    qs.forEach((q) => {
      const diff = getDiffConfig(q.difficulty);
      lines.push(`Q${globalIndex}. [${diff.label}] ${q.question}`);
      if (q.answer) {
        lines.push("");
        lines.push(`   Answer:`);
        q.answer.split("\n").forEach((l) => lines.push(`   ${l}`));
      }
      if (q.related_skill) {
        lines.push(`   Related Skill: ${q.related_skill}`);
      }
      lines.push("");
      globalIndex++;
    });
  });

  lines.push("═".repeat(60));
  lines.push("  Generated by TrustLoom AI — trustloom.ai");
  lines.push("═".repeat(60));
  return lines.join("\n");
}

// ─── Sub-components ──────────────────────────────────────────────────────────

/** Single question card */
const QuestionCard = React.memo(function QuestionCard({ q, index, globalIndex }) {
  const [showAnswer, setShowAnswer] = useState(false);
  const [copied, setCopied] = useState(false);
  const catCfg = getCatConfig(q.category);
  const diffCfg = getDiffConfig(q.difficulty);
  const hasAnswer = !!q.answer;

  const handleCopy = useCallback(async () => {
    let text = `Q${globalIndex}. ${q.question}`;
    if (q.answer) text += `\n\nAnswer: ${q.answer}`;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* ignore */
    }
  }, [q, globalIndex]);

  return (
    <div className="iq-question-card" style={{ "--cat-color": catCfg.color }}>
      {/* Top row: number + difficulty + copy */}
      <div className="iq-q-top">
        <span className="iq-q-number" style={{ background: catCfg.color }}>
          Q{globalIndex}
        </span>
        <span
          className="iq-q-difficulty"
          style={{ background: diffCfg.bg, color: diffCfg.color }}
        >
          {diffCfg.label}
        </span>
        {q.related_skill && (
          <span className="iq-q-skill">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
            </svg>
            {q.related_skill}
          </span>
        )}
        <button
          className={`iq-q-copy ${copied ? "copied" : ""}`}
          onClick={handleCopy}
          title={copied ? "Copied!" : "Copy question"}
        >
          {copied ? (
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
          ) : (
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" /></svg>
          )}
        </button>
      </div>

      {/* Question text */}
      <p className="iq-q-text">{q.question}</p>

      {/* Answer section */}
      {hasAnswer ? (
        <div className="iq-q-answer-wrap">
          <button
            className={`iq-q-answer-toggle ${showAnswer ? "open" : ""}`}
            onClick={() => setShowAnswer((v) => !v)}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10" /><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /><line x1="12" y1="17" x2="12.01" y2="17" />
            </svg>
            <span>{showAnswer ? "Hide Answer" : "Show Expected Answer"}</span>
            <svg
              className={`iq-toggle-chevron ${showAnswer ? "rotated" : ""}`}
              width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
            >
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
          {showAnswer && (
            <div className="iq-q-answer-body">
              <div className="iq-q-answer-label">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
                Expected Answer
              </div>
              <div className="iq-q-answer-text">{q.answer}</div>
            </div>
          )}
        </div>
      ) : (
        <div className="iq-q-no-answer">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><line x1="12" y1="16" x2="12" y2="12" /><line x1="12" y1="8" x2="12.01" y2="8" /></svg>
          <span>Candidate-specific — evaluate based on their actual experience</span>
        </div>
      )}
    </div>
  );
});

/** Category accordion section */
const CategorySection = React.memo(function CategorySection({
  catKey,
  questions,
  expanded,
  onToggle,
  globalOffset,
}) {
  const cfg = getCatConfig(catKey);
  const answeredCount = questions.filter((q) => q.answer).length;

  return (
    <div className={`iq-cat-section ${expanded ? "expanded" : ""}`}>
      <button
        className="iq-cat-header"
        onClick={onToggle}
        style={{ "--cat-color": cfg.color, "--cat-gradient": cfg.gradient, "--cat-light": cfg.light }}
      >
        <div className="iq-cat-left">
          <div className="iq-cat-icon-wrap" style={{ background: cfg.light, color: cfg.color }}>
            {cfg.icon}
          </div>
          <div className="iq-cat-info">
            <span className="iq-cat-name">{cfg.label}</span>
            <span className="iq-cat-desc">{cfg.description}</span>
          </div>
        </div>
        <div className="iq-cat-right">
          <span className="iq-cat-count">{questions.length}</span>
          {answeredCount > 0 && (
            <span className="iq-cat-answered">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
              {answeredCount} with answers
            </span>
          )}
          <svg
            className={`iq-cat-chevron ${expanded ? "rotated" : ""}`}
            width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        </div>
      </button>

      {expanded && (
        <div className="iq-cat-body">
          {questions.map((q, i) => (
            <QuestionCard
              key={`${catKey}-${i}`}
              q={q}
              index={i}
              globalIndex={globalOffset + i + 1}
            />
          ))}
        </div>
      )}
    </div>
  );
});

// ─── Main component ──────────────────────────────────────────────────────────

export default function InterviewQuestions({
  questions = [],
  categories = {},
  metadata = {},
  onClose,
  onRegenerate,
}) {
  // Expand state per category — all expanded by default
  const sortedCatKeys = useMemo(() => {
    const order = ["technical", "project", "general", "red_flag", "behavioral"];
    return Object.keys(categories)
      .filter((k) => categories[k]?.length > 0)
      .sort((a, b) => {
        const ia = order.indexOf(a);
        const ib = order.indexOf(b);
        return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
      });
  }, [categories]);

  const [expandedCats, setExpandedCats] = useState(() => {
    const init = {};
    sortedCatKeys.forEach((k) => (init[k] = true));
    return init;
  });

  const [copyState, setCopyState] = useState("idle"); // idle | copied | error
  const [isRegenerating, setIsRegenerating] = useState(false);
  const containerRef = useRef(null);

  // Lock body scroll while modal is open
  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = prev; };
  }, []);

  // Close on Escape key
  useEffect(() => {
    const handleKey = (e) => { if (e.key === "Escape") onClose?.(); };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onClose]);

  const totalQuestions = questions.length;
  const answeredCount = questions.filter((q) => q.answer).length;

  // Toggle individual category
  const toggleCat = useCallback((key) => {
    setExpandedCats((prev) => ({ ...prev, [key]: !prev[key] }));
  }, []);

  // Expand / Collapse all
  const setAllExpanded = useCallback(
    (val) => {
      const next = {};
      sortedCatKeys.forEach((k) => (next[k] = val));
      setExpandedCats(next);
    },
    [sortedCatKeys]
  );

  // Copy all
  const handleCopyAll = useCallback(async () => {
    try {
      const text = buildPlainText(categories);
      await navigator.clipboard.writeText(text);
      setCopyState("copied");
      setTimeout(() => setCopyState("idle"), 2200);
    } catch {
      setCopyState("error");
      setTimeout(() => setCopyState("idle"), 2200);
    }
  }, [categories]);

  // Download as TXT
  const handleDownloadTxt = useCallback(() => {
    const text = buildPlainText(categories);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TrustLoom_Interview_Questions_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [categories]);

  // Download as PDF (uses browser print)
  const handleDownloadPdf = useCallback(() => {
    // Build a standalone HTML string and open in a new window for printing
    const text = buildPlainText(categories);
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>TrustLoom AI — Interview Questions</title>
  <style>
    @page { margin: 1.5cm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1f2937; line-height: 1.6; padding: 40px; }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #e5e7eb; }
    .header h1 { font-size: 24px; color: #667eea; margin-bottom: 4px; }
    .header p { font-size: 13px; color: #6b7280; }
    .category { margin-bottom: 28px; }
    .cat-title { font-size: 16px; font-weight: 700; color: #ffffff; padding: 10px 16px; border-radius: 8px; margin-bottom: 14px; }
    .cat-technical { background: linear-gradient(135deg, #3b82f6, #2563eb); }
    .cat-project { background: linear-gradient(135deg, #f59e0b, #d97706); }
    .cat-general { background: linear-gradient(135deg, #8b5cf6, #7c3aed); }
    .cat-red_flag { background: linear-gradient(135deg, #ef4444, #dc2626); }
    .cat-behavioral { background: linear-gradient(135deg, #10b981, #059669); }
    .q-card { border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px; margin-bottom: 12px; page-break-inside: avoid; }
    .q-top { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
    .q-num { background: #667eea; color: #fff; font-size: 12px; font-weight: 700; padding: 3px 8px; border-radius: 4px; }
    .q-diff { font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
    .q-diff.junior { background: #d1fae5; color: #065f46; }
    .q-diff.mid { background: #fef3c7; color: #92400e; }
    .q-diff.senior { background: #fee2e2; color: #991b1b; }
    .q-skill { font-size: 11px; color: #3b82f6; background: #dbeafe; padding: 2px 8px; border-radius: 4px; }
    .q-text { font-size: 14px; line-height: 1.6; color: #1f2937; margin-bottom: 10px; }
    .answer-box { background: #f0fdf4; border-left: 3px solid #10b981; padding: 12px 14px; border-radius: 0 8px 8px 0; }
    .answer-label { font-size: 11px; font-weight: 700; color: #059669; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
    .answer-text { font-size: 13px; color: #065f46; line-height: 1.6; white-space: pre-wrap; }
    .no-answer { font-size: 12px; color: #92400e; background: #fef3c7; padding: 8px 12px; border-radius: 6px; font-style: italic; }
    .footer { text-align: center; margin-top: 32px; padding-top: 16px; border-top: 2px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
  </style>
</head>
<body>
  <div class="header">
    <h1>TrustLoom AI — Interview Questions</h1>
    <p>Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}</p>
    <p>${totalQuestions} questions · ${answeredCount} with expected answers</p>
  </div>
  ${sortedCatKeys.map((catKey) => {
    const cfg = getCatConfig(catKey);
    const qs = categories[catKey];
    if (!qs || qs.length === 0) return "";
    let offset = 0;
    for (const ck of sortedCatKeys) {
      if (ck === catKey) break;
      offset += (categories[ck]?.length || 0);
    }
    return `
    <div class="category">
      <div class="cat-title cat-${catKey}">${cfg.label} (${qs.length})</div>
      ${qs.map((q, i) => {
        const diff = getDiffConfig(q.difficulty);
        return `
        <div class="q-card">
          <div class="q-top">
            <span class="q-num">Q${offset + i + 1}</span>
            <span class="q-diff ${q.difficulty?.toLowerCase() || 'mid'}">${diff.label}</span>
            ${q.related_skill ? `<span class="q-skill">${q.related_skill}</span>` : ""}
          </div>
          <div class="q-text">${q.question}</div>
          ${q.answer ? `
          <div class="answer-box">
            <div class="answer-label">Expected Answer</div>
            <div class="answer-text">${q.answer}</div>
          </div>` : `<div class="no-answer">Candidate-specific — evaluate based on their actual experience</div>`}
        </div>`;
      }).join("")}
    </div>`;
  }).join("")}
  <div class="footer">Generated by TrustLoom AI</div>
</body>
</html>`;

    const printWindow = window.open("", "_blank", "width=800,height=900");
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 400);
    }
  }, [categories, sortedCatKeys, totalQuestions, answeredCount]);

  // Regenerate wrapper
  const handleRegenerate = useCallback(async () => {
    setIsRegenerating(true);
    try {
      await onRegenerate?.();
    } finally {
      setIsRegenerating(false);
    }
  }, [onRegenerate]);

  // Compute global offsets per category
  const globalOffsets = useMemo(() => {
    const offsets = {};
    let running = 0;
    sortedCatKeys.forEach((k) => {
      offsets[k] = running;
      running += categories[k]?.length || 0;
    });
    return offsets;
  }, [sortedCatKeys, categories]);

  // If no questions at all
  if (!questions || questions.length === 0) {
    return (
      <div className="iq-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose?.(); }}>
        <div className="iq-panel" ref={containerRef}>
          <div className="iq-panel-header">
            <div className="iq-panel-title-row">
              <div className="iq-panel-title-group">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /><line x1="12" y1="17" x2="12.01" y2="17" /></svg>
                <h2>Interview Questions</h2>
              </div>
              <button className="iq-panel-close" onClick={onClose} aria-label="Close">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" /></svg>
              </button>
            </div>
          </div>
          <div className="iq-empty">
            <div className="iq-empty-icon">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /><line x1="12" y1="17" x2="12.01" y2="17" /></svg>
            </div>
            <p>No interview questions generated yet.</p>
            <button className="iq-empty-btn" onClick={handleRegenerate}>
              Generate Questions
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="iq-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose?.(); }}>
      <div className="iq-panel" ref={containerRef}>
      {/* ── Header ─────────────────────────────────────────── */}
      <div className="iq-panel-header">
        <div className="iq-panel-title-row">
          <div className="iq-panel-title-group">
            <div className="iq-panel-icon">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /><line x1="12" y1="17" x2="12.01" y2="17" /></svg>
            </div>
            <div>
              <h2>Interview Questions</h2>
              <p className="iq-panel-subtitle">AI-generated questions tailored to this candidate</p>
            </div>
          </div>
          <button className="iq-panel-close" onClick={onClose} aria-label="Close">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" /></svg>
          </button>
        </div>

        {/* Summary stats */}
        <div className="iq-stats-row">
          <div className="iq-stat">
            <span className="iq-stat-value">{totalQuestions}</span>
            <span className="iq-stat-label">Total Questions</span>
          </div>
          <div className="iq-stat">
            <span className="iq-stat-value">{answeredCount}</span>
            <span className="iq-stat-label">With Answers</span>
          </div>
          <div className="iq-stat">
            <span className="iq-stat-value">{sortedCatKeys.length}</span>
            <span className="iq-stat-label">Categories</span>
          </div>
          {metadata?.experience_level && (
            <div className="iq-stat">
              <span className="iq-stat-value">{metadata.experience_level}</span>
              <span className="iq-stat-label">Level</span>
            </div>
          )}
        </div>

        {/* Metadata badges */}
        {metadata && (
          <div className="iq-meta-badges">
            {metadata.skills_count > 0 && (
              <span className="iq-meta-badge blue">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" /></svg>
                {metadata.skills_count} Skills
              </span>
            )}
            {metadata.projects_count > 0 && (
              <span className="iq-meta-badge amber">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" /></svg>
                {metadata.projects_count} Projects
              </span>
            )}
            {metadata.processing_time_ms && (
              <span className="iq-meta-badge purple">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><polyline points="12 6 12 12 16 14" /></svg>
                {metadata.processing_time_ms}ms
              </span>
            )}
          </div>
        )}
      </div>

      {/* ── Action bar ─────────────────────────────────────── */}
      <div className="iq-action-bar">
        <div className="iq-action-left">
          {/* Download buttons */}
          <div className="iq-download-group">
            <button className="iq-btn iq-btn-download" onClick={handleDownloadTxt}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
              Download TXT
            </button>
            <button className="iq-btn iq-btn-download-pdf" onClick={handleDownloadPdf}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" /><polyline points="10 9 9 9 8 9" /></svg>
              Download PDF
            </button>
          </div>
        </div>

        <div className="iq-action-right">
          <button className="iq-btn iq-btn-ghost" onClick={() => setAllExpanded(true)}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 3 21 3 21 9" /><polyline points="9 21 3 21 3 15" /><line x1="21" y1="3" x2="14" y2="10" /><line x1="3" y1="21" x2="10" y2="14" /></svg>
            Expand All
          </button>
          <button className="iq-btn iq-btn-ghost" onClick={() => setAllExpanded(false)}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="4 14 10 14 10 20" /><polyline points="20 10 14 10 14 4" /><line x1="14" y1="10" x2="21" y2="3" /><line x1="3" y1="21" x2="10" y2="14" /></svg>
            Collapse All
          </button>
        </div>
      </div>

      {/* ── Category sections ──────────────────────────────── */}
      <div className="iq-body">
        {sortedCatKeys.map((catKey) => (
          <CategorySection
            key={catKey}
            catKey={catKey}
            questions={categories[catKey]}
            expanded={!!expandedCats[catKey]}
            onToggle={() => toggleCat(catKey)}
            globalOffset={globalOffsets[catKey]}
          />
        ))}
      </div>

      {/* ── Footer ─────────────────────────────────────────── */}
      <div className="iq-footer">
        <span>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" /></svg>
          Powered by Gemini AI
        </span>
        <span className="iq-footer-tip">
          Click on a question to see the expected answer · Use download to save
        </span>
      </div>
    </div>
    </div>
  );
}
